name: Release

on:
  push:
    branches:
      - 'main'

env:
  #TODO add these as github secrets
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PRODUCTION_KEY_ALIAS: ${{ secrets.PRODUCTION_KEY_ALIAS }}
  PRODUCTION_KEY_PASSWORD: ${{ secrets.PRODUCTION_KEY_PASSWORD }}
  PRODUCTION_STORE_FILE: ${{ secrets.PRODUCTION_STORE_FILE }}
  PRODUCTION_STORE_PASSWORD: ${{ secrets.PRODUCTION_STORE_PASSWORD }}
  SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  #For Firebase Apps
  #FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

jobs:
  deploy:
    name: Android Release
    runs-on: ubuntu-latest

    steps:
      # Step 1 Checkout
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # For Firebase Apps
      # Step 2 Decode Google services file
      #- name: Decode google-services.json
        #run: |
          #echo $FIREBASE_CONFIG > app/google-services.json

      # Cache
      - name: Cache Gradle Files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle

      # Lint
      - name: Run Android Linter
        run: ./gradlew lint

      # Unit Test
      - name: Unit tests
        run: bash ./gradlew test
      - name: Save Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results
          path: app/build/test-results/testReleaseUnitTest/*.xml

      # Semantic release
      ## Creates apk using assemble in the .releaserc file
      ## Updates Build Number
      ## Commits changes and creates Tag
      ## Create Github Release with Release Notes (uses Angular Commit Message Conventions)
      ### Please use commitizen to make valid commit messages.
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/changelog@6
            @semantic-release/git@10
          semantic_version: 18.0.0

      # Google Play Deploy
      - name: Google Play Deploy
        uses: r0adkll/upload-google-play@v1.0.16
        with:
          serviceAccountJsonPlainText: $SERVICE_ACCOUNT_JSON
          ##TODO Change package name
          packageName: com.hattrick.myapplication
          releaseFiles: app/build/outputs/bundle/release/*.aab
          #TODO Set desired track
          track: internal
          status: completed
          inAppUpdatePriority: 5

      # Slack Notification
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{ github.event.head_commit.message }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: Release
          SLACK_ICON: https://media-exp1.licdn.com/dms/image/C4E0BAQEmSneWeuqZJQ/company-logo_200_200/0/1589546919698?e=2159024400&v=beta&t=jp8a6n1opDcCZOOpR4v5qNXKOfZG_hk0MIT531rnsH8
          #TODO generate webhook with https://slack.com/apps/A0F7XDUAZ-incoming-webhooks and save it in github secrets
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}